global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot'
    static_configs:
      - targets: ['otel-collector.ru']
        labels:
          application: 'muffin-wallet'

#  - job_name: postgres
#    static_configs:
#      - targets: ['127.0.0.1:9187']
