apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-promtail-config
  labels:
    app: {{ .Values.name }}
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: {{ .Values.promtail.lokiUrl }}

    scrape_configs:
      - job_name: app-logs
        pipeline_stages:
          - regex:
              expression: '^(?P<timestamp>\S+)\s+(?P<logLevel>INFO|ERROR|WARN|DEBUG)\s+\[(?P<traceId>[a-f0-9]*),(?P<spanId>[a-f0-9]*)\]'

          - labels:
              traceId:
              logLevel:
        static_configs:
          - targets:
              - localhost
            labels:
              job: {{ .Values.name }}
              __path__: /logs/*.log
