apiVersion: 1

datasources:
  - name: loki
    type: loki
    access: proxy
    url: http://host.docker.internal:3100
    isDefault: true

  - name: zipkin
    type: zipkin
    access: proxy
    url: http://host.docker.internal:9411
    isDefault: false

  - name: prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090
    isDefault: false