apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otel-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: otel-collector.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: otel-collector-collector
                port:
                  number: 8889